// Copyright © Cysharp, Inc. All rights reserved.
// This source code is licensed under the MIT License. See details at https://github.com/Cysharp/SlnMerge.

// ReSharper disable All

using System;
using System.Diagnostics.CodeAnalysis;
using System.IO;

namespace SlnMerge
{
    public static class SlnMerge
    {
        public static bool TryMerge(string solutionFilePath, string solutionFileContent, ProcessingPolicyOverride processingPolicyOverride, ISlnMergeLogger logger, [NotNullWhen(true)] out string? resultSolutionContent)
        {
            // Load SlnMerge settings from .mergesettings
            var slnFileDirectory = Path.GetDirectoryName(solutionFilePath);
            if (SlnMergeSettings.TryLoadBySolutionPath(solutionFilePath, out var slnMergeSettingsPath, out var slnMergeSettings))
            {
                logger.Debug($"Using SlnMerge Settings: {slnMergeSettingsPath}");
            }
            else
            {
                logger.Debug($"No SlnMerge settings found.");
            }

            return TryMerge(solutionFilePath, solutionFileContent, slnMergeSettings, processingPolicyOverride, logger, out resultSolutionContent);
        }

        public static bool TryMerge(string solutionFilePath, string solutionFileContent, SlnMergeSettings? slnMergeSettings, ProcessingPolicyOverride processingPolicyOverride, ISlnMergeLogger logger, [NotNullWhen(true)] out string? resultSolutionContent)
        {
            logger.Debug(solutionFileContent);
            try
            {
                var solutionName = Path.GetFileNameWithoutExtension(solutionFilePath);
                var isSlnx = Path.GetExtension(solutionFilePath) == ".slnx";
                var slnFileDirectory = Path.GetDirectoryName(solutionFilePath);

                if (slnMergeSettings is null || slnMergeSettings.Disabled)
                {
                    logger.Debug("SlnMerge is currently disabled.");
                    resultSolutionContent = solutionFileContent;
                    return true;
                }

                var processingPolicy = processingPolicyOverride is ProcessingPolicyOverride.Unspecified
                    ? slnMergeSettings.DefaultProcessingPolicy
                    : (ProcessingPolicy)processingPolicyOverride;
                if (processingPolicy == ProcessingPolicy.Disabled)
                {
                    logger.Debug($"SlnMerge is currently disabled by policy. (ProcessingPolicy: {processingPolicy})");
                    resultSolutionContent = solutionFileContent;
                    return true;
                }

                // Determine a overlay solution path.
                var overlaySolutionFilePath = slnMergeSettings.MergeTargetSolution;
                var overlaySolutionFileContent = default(string);

                // If MergeTargetSolution is not specified, or the policy is NestedProjectOnly, use an empty solution.
                if (string.IsNullOrWhiteSpace(overlaySolutionFilePath) || processingPolicy == ProcessingPolicy.NestedProjectOnly)
                {
                    // Use an empty solution implicitly
                    overlaySolutionFilePath = $"{solutionName}.Empty.AutoGenerated.slnx";
                    overlaySolutionFileContent = "<Solution />";
                }
                else
                {
                    overlaySolutionFilePath = PathHelper.NormalizePath(Path.Combine(slnFileDirectory, slnMergeSettings.MergeTargetSolution));
                }

                if (overlaySolutionFileContent is null)
                {
                    if (!File.Exists(overlaySolutionFilePath))
                    {
                        logger.Warn($"Cannot load the solution file to merge. skipped: {overlaySolutionFilePath}");
                        resultSolutionContent = null;
                        return false;
                    }
                    overlaySolutionFileContent = File.ReadAllText(overlaySolutionFilePath);
                }

                // Merge the solutions.
                logger.Debug($"Start merging: Base={solutionFilePath}; Overlay={overlaySolutionFilePath}; ProcessingPolicy={processingPolicy}");

                var succeeded = SolutionMerger.TryMerge(
                    solutionFilePath,
                    solutionFileContent,
                    overlaySolutionFilePath,
                    overlaySolutionFileContent,
                    slnMergeSettings,
                    logger,
                    out resultSolutionContent);

                logger.Debug($"TryMerge: Succeeded:{succeeded}\n{resultSolutionContent}");

                return succeeded;
            }
            catch (Exception e)
            {
                logger.Error("Failed to merge the solutions", e);
                resultSolutionContent = null;
                return false;
            }

        }
    }
}
