name: Build-Test

on:
  push:
    branches:
      - master
    tags:
      - "!*" # not a tag push
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  BuildAndRunTests:
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[ci skip]'))"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet build -c Debug test/SlnMerge.Tests
      - run: dotnet test -c Debug --no-build test/SlnMerge.Tests
